# Generated by Django 4.2.2 on 2024-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='shares_traded',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='turnover',
            field=models.FloatField(),
        ),
    ]
